import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

test("settings tabs use query parameters with profile fallback", async () => {
  const source = await readFile(new URL("./SettingsPage.jsx", import.meta.url), "utf8");
  const css = await readFile(new URL("../index.css", import.meta.url), "utf8");
  assert.match(source, /tab=profile/);
  assert.match(source, /tab=categories/);
  assert.match(source, /tab=units/);
  assert.match(source, /Profil toko/);
  assert.match(source, /MasterDataManager/);
  assert.match(source, /SettingsNavigation/);
  assert.match(source, /className="settings-workspace min-h-0 flex-1 overflow-auto"/);
  assert.match(source, /className="settings-workspace-layout"/);
  assert.doesNotMatch(source, /md:grid-cols-\[14rem_minmax\(0,1fr\)\]/);
  assert.match(source, /max-w-3xl/);
  assert.doesNotMatch(source, /Current store/);
  assert.doesNotMatch(source, /Local MVP/);
  assert.match(source, /const \{ loadCategories, loadSettings, loadUnits \} = store;/);
  assert.match(source, /\[loadCategories, loadSettings, loadUnits, tab\]/);
  assert.doesNotMatch(source, /\[store, tab\]/);
  assert.match(css, /\.settings-workspace\s*\{[\s\S]*container-name:\s*settings-workspace;[\s\S]*container-type:\s*inline-size;/);
  assert.doesNotMatch(css, /@container settings-workspace \(min-width:\s*760px\)/);
  assert.doesNotMatch(css, /grid-template-columns:\s*14rem minmax\(0,\s*1fr\)/);
  assert.match(source, /import \{ motion, useReducedMotion \} from "motion\/react";/);
  assert.match(source, /getSettingsTabDirection/);
  assert.match(source, /const previousTabRef = React\.useRef\(tab\);/);
  assert.match(source, /const hasRenderedTabRef = React\.useRef\(false\);/);
  assert.match(source, /if \(isInitialLoad\) return;/);
  assert.match(source, /key=\{tab\}/);
  assert.match(source, /x: shouldReduceMotion \? 0 : direction \* 20/);
  assert.match(source, /type: "spring", bounce: 0, duration: 0\.28/);
  assert.match(source, /duration: 0\.14, ease: "easeOut"/);
  assert.match(source, /initial=\{shouldAnimate/);
  assert.match(css, /\.settings-content\s*\{[\s\S]*overflow-x:\s*clip/);
  assert.match(source, /useScanSoundPreference/);
  assert.match(source, /role="switch"/);
  assert.match(source, /Bunyi pemindaian/);
  assert.match(source, /settings-profile-form grid gap-4/);
  assert.match(source, /<Switch checked=\{scanSoundEnabled\} tone="success" decorative \/>/);
  assert.match(source, /aria-checked=\{Boolean\(draft\.taxEnabled\)\}/);
  assert.match(source, /<Switch checked=\{Boolean\(draft\.taxEnabled\)\} tone="success" decorative \/>/);
  assert.match(source, /disabled: !draft\.taxEnabled \|\| isSaving/);
  assert.doesNotMatch(source, /type="checkbox"/);
  assert.doesNotMatch(source, /<Icon name="check"/);
  assert.doesNotMatch(source, /settings-form-actions/);
});
