export const categories = [
  "All",
  "Appetizers",
  "Main Course",
  "Noodles & Rice",
  "Desserts",
  "Drinks",
  "Soups",
  "Vegetarian",
  "Seafood",
];

export const menuItems = [
  {
    name: "Spicy Shrimp Rice",
    category: "Seafood",
    price: "$ 8.99",
    qty: 0,
    image: "/images/spicy-shrimp-rice.png",
  },
  {
    name: "Classic Beef Burger",
    category: "Main Course",
    price: "$ 6.50",
    qty: 0,
    image: "/images/classic-beef-burger.png",
  },
  {
    name: "Garlic Bread Sticks",
    category: "Appetizers",
    price: "$ 3.25",
    qty: 0,
    image: "/images/garlic-bread-sticks.png",
  },
  {
    name: "Thai Tom Yum Soup",
    category: "Soups",
    price: "$ 5.75",
    qty: 0,
    image: "/images/thai-tom-yum-soup.png",
  },
  {
    name: "Chicken Teriyaki Bowl",
    category: "Noodles & Rice",
    price: "$ 7.99",
    qty: 1,
    image: "/images/chicken-teriyaki-bowl.png",
  },
  {
    name: "Iced Matcha Latte",
    category: "Drinks",
    price: "$ 4.20",
    qty: 0,
    image: "/images/iced-matcha-latte.png",
  },
  {
    name: "Grilled Salmon Fillet",
    category: "Seafood",
    price: "$ 11.25",
    qty: 0,
    image: "/images/grilled-salmon-fillet.png",
  },
  {
    name: "Veggie Fried Rice",
    category: "Vegetarian",
    price: "$ 6.00",
    qty: 0,
    image: "/images/veggie-fried-rice.png",
  },
  {
    name: "BBQ Chicken Wings",
    category: "Appetizers",
    price: "$ 7.99",
    qty: 0,
    image: "/images/bbq-chicken-wings.png",
  },
  {
    name: "Pad Thai Chicken",
    category: "Noodles & Rice",
    price: "$ 4.20",
    qty: 2,
    image: "/images/pad-thai-chicken.png",
  },
  {
    name: "Hot Americano",
    category: "Drinks",
    price: "$ 2.80",
    qty: 2,
    image: "/images/hot-americano.png",
  },
  {
    name: "Vegan Buddha Bowl",
    category: "Vegetarian",
    price: "$ 7.10",
    qty: 0,
    image: "/images/vegan-buddha-bowl.png",
  },
  {
    name: "Caesar Salad",
    category: "Appetizers",
    price: "$ 5.50",
    qty: 0,
    image: "/images/garlic-bread-sticks.png",
  },
  {
    name: "Beef Rendang",
    category: "Main Course",
    price: "$ 10.50",
    qty: 0,
    image: "/images/classic-beef-burger.png",
  },
  {
    name: "Miso Soup",
    category: "Soups",
    price: "$ 4.00",
    qty: 0,
    image: "/images/thai-tom-yum-soup.png",
  },
  {
    name: "Fried Calamari",
    category: "Appetizers",
    price: "$ 6.75",
    qty: 0,
    image: "/images/spicy-shrimp-rice.png",
  },
  {
    name: "Nasi Goreng",
    category: "Noodles & Rice",
    price: "$ 7.25",
    qty: 0,
    image: "/images/veggie-fried-rice.png",
  },
  {
    name: "Mango Sticky Rice",
    category: "Desserts",
    price: "$ 5.00",
    qty: 0,
    image: "/images/vegan-buddha-bowl.png",
  },
  {
    name: "Iced Lemon Tea",
    category: "Drinks",
    price: "$ 2.50",
    qty: 0,
    image: "/images/iced-matcha-latte.png",
  },
  {
    name: "Fish & Chips",
    category: "Main Course",
    price: "$ 9.25",
    qty: 0,
    image: "/images/grilled-salmon-fillet.png",
  },
  {
    name: "Spring Rolls",
    category: "Appetizers",
    price: "$ 4.50",
    qty: 0,
    image: "/images/bbq-chicken-wings.png",
  },
  {
    name: "Chocolate Lava Cake",
    category: "Desserts",
    price: "$ 6.20",
    qty: 0,
    image: "/images/pad-thai-chicken.png",
  },
  {
    name: "Tomato Basil Soup",
    category: "Soups",
    price: "$ 4.80",
    qty: 0,
    image: "/images/thai-tom-yum-soup.png",
  },
  {
    name: "Fresh Orange Juice",
    category: "Drinks",
    price: "$ 3.80",
    qty: 0,
    image: "/images/hot-americano.png",
  },
];

export const orderItems = [
  {
    name: "Chicken Teriyaki Bowl",
    quantity: "x2",
    image: "/images/chicken-teriyaki-bowl.png",
    addons: ["Extra Chili (+$0.50)", "Add Egg (+$1.00)"],
    subtotal: "$10.49",
  },
  {
    name: "Hot Americano",
    quantity: "x2",
    image: "/images/hot-americano.png",
    addons: ["Extra Shot (+$1.00)", "Oat Milk (+$0.70)"],
    subtotal: "$4.50",
  },
  {
    name: "BBQ Chicken Wings",
    quantity: "x1",
    image: "/images/bbq-chicken-wings.png",
    addons: ["Extra Dip (+$0.50)"],
    subtotal: "$7.99",
  },
  {
    name: "Pad Thai Chicken",
    quantity: "x1",
    image: "/images/pad-thai-chicken.png",
    addons: ["Extra Chili (+$0.50)", "Peanuts (+$0.75)"],
    subtotal: "$5.45",
  },
];

export const transactionData = [
  { id: "TRX-001", time: "09:42 AM", items: 4, total: 32.50, payment: "Cash", status: "completed", cashier: "Ari" },
  { id: "TRX-002", time: "10:15 AM", items: 2, total: 15.80, payment: "QR", status: "completed", cashier: "Sari" },
  { id: "TRX-003", time: "10:27 AM", items: 1, total: 6.50, payment: "Card", status: "refunded", cashier: "Ari" },
  { id: "TRX-004", time: "11:00 AM", items: 6, total: 48.20, payment: "Cash", status: "completed", cashier: "Budi" },
  { id: "TRX-005", time: "11:35 AM", items: 3, total: 22.75, payment: "QR", status: "completed", cashier: "Sari" },
  { id: "TRX-006", time: "12:10 PM", items: 5, total: 39.90, payment: "Card", status: "completed", cashier: "Ari" },
  { id: "TRX-007", time: "12:45 PM", items: 2, total: 11.40, payment: "Cash", status: "voided", cashier: "Budi" },
  { id: "TRX-008", time: "01:20 PM", items: 8, total: 72.60, payment: "QR", status: "completed", cashier: "Sari" },
  { id: "TRX-009", time: "01:55 PM", items: 1, total: 4.20, payment: "Cash", status: "completed", cashier: "Ari" },
  { id: "TRX-010", time: "02:30 PM", items: 3, total: 28.50, payment: "Card", status: "completed", cashier: "Budi" },
];

export const inventoryData = [
  { sku: "BVR-001", name: "Beef Patty", category: "Protein", stock: 48, min: 20, unit: "pcs", cost: 2.50 },
  { sku: "BVR-002", name: "Chicken Thigh", category: "Protein", stock: 35, min: 15, unit: "kg", cost: 3.80 },
  { sku: "BVR-003", name: "Basmati Rice", category: "Dry Goods", stock: 12, min: 10, unit: "kg", cost: 1.50 },
  { sku: "BVR-004", name: "Garlic", category: "Produce", stock: 3, min: 5, unit: "kg", cost: 0.80 },
  { sku: "BVR-005", name: "Shrimp", category: "Seafood", stock: 8, min: 8, unit: "kg", cost: 6.20 },
  { sku: "BVR-006", name: "Cooking Oil", category: "Dry Goods", stock: 22, min: 10, unit: "L", cost: 2.00 },
  { sku: "BVR-007", name: "Milk", category: "Dairy", stock: 6, min: 10, unit: "L", cost: 1.40 },
  { sku: "BVR-008", name: "Ice Cream Base", category: "Dairy", stock: 15, min: 5, unit: "kg", cost: 3.20 },
];

export const tokenGroups = [
  {
    name: "Color",
    tokens: [
      ["Background", "--color-app-bg", "#fafafa"],
      ["Surface", "--color-surface", "#ffffff"],
      ["Muted Surface", "--color-surface-muted", "#f6f6f6"],
      ["Border", "--color-border", "#ececec"],
      ["Strong Border", "--color-border-strong", "#d9d9d9"],
      ["Text", "--color-text", "#242424"],
      ["Muted Text", "--color-text-muted", "#6f6f6f"],
      ["Subtle Text", "--color-text-subtle", "#a1a1a1"],
      ["Accent", "--color-accent", "#1d1d1f"],
      ["Accent Hover", "--color-accent-hover", "#000000"],
      ["Accent Soft", "--color-accent-soft", "#f2f2f3"],
      ["Danger", "--color-danger", "#ef4444"],
      ["Danger Soft", "--color-danger-soft", "#fff1f1"],
      ["Success", "--color-success", "#168a4a"],
      ["Success Soft", "--color-success-soft", "#eaf7ef"],
      ["Warning", "--color-warning", "#ad6a00"],
      ["Warning Soft", "--color-warning-soft", "#fff4da"],
      ["Focus", "--color-focus", "#4a4a4d"],
    ],
  },
  {
    name: "Radius",
    tokens: [
      ["Control", "--radius-control", "10px"],
      ["Card", "--radius-card", "12px"],
      ["Panel", "--radius-panel", "20px"],
    ],
  },
  {
    name: "Shadow",
    tokens: [
      ["Low", "--shadow-low", "0 1px 2px rgb(0 0 0 / 0.05)"],
      ["Panel", "--shadow-panel", "0 18px 45px rgb(18 18 18 / 0.06)"],
      ["Accent", "--shadow-accent", "0 12px 22px rgb(29 29 31 / 0.18)"],
      ["Inner Soft", "--shadow-inner-soft", "inset 0 0 0 1px rgb(0 0 0 / 0.01)"],
    ],
  },
  {
    name: "Motion",
    tokens: [
      ["Fast", "--duration-fast", "120ms"],
      ["Base", "--duration-base", "180ms"],
      ["Slow", "--duration-slow", "280ms"],
      ["Ease", "--ease-standard", "cubic-bezier(0.2, 0, 0, 1)"],
    ],
  },
  {
    name: "Typography",
    tokens: [
      ["Sans", "--font-sans", "Manrope, Inter, system-ui, sans-serif"],
      ["Mono", "--font-mono", "JetBrains Mono, ui-monospace, monospace"],
      ["Body", "text-base", "16px / 1.5 (Manrope 500)"],
      ["Heading", "text-2xl", "24px / 1.3 (Manrope 600)"],
      ["Display", "text-3xl", "30px / 1.2 (Manrope 700)"],
      ["Value", "font-mono", "tabular-nums (JetBrains Mono 500)"],
    ],
  },
];
